---
- name: Generate AWS keypair and store it in credstash
  ec2_key:
    name: "{{ stack }}"
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
  register: ec2_key

- debug: var=ec2_key

- name: Store ec2 private key with credstash
  shell: "/usr/local/bin/credstash -r {{ region }} -p {{ aws_profile  }} put ec2_key_{{ stack }} \"{{ ec2_key.key.private_key }}\""
  when: ec2_key.key.private_key is defined
